package com.demo.web.dao;

import com.demo.web.entities.Goods;
import com.demo.web.entities.GoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	long countByExample(GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	int deleteByExample(GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	int insert(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	int insertSelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	List<Goods> selectByExample(GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Goods record, @Param("example") GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	int updateByExample(@Param("record") Goods record, @Param("example") GoodsExample example);
}