package com.demo.web.entities;

import java.io.Serializable;

import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import java.math.BigDecimal;

/**
 * 商品实体
 *
 */
public class Goods implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.id
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.name
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.price
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.picture
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	private String picture;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.id
	 * @return  the value of goods.id
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.id
	 * @param id  the value for goods.id
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.name
	 * @return  the value of goods.name
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.name
	 * @param name  the value for goods.name
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.price
	 * @return  the value of goods.price
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.price
	 * @param price  the value for goods.price
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.picture
	 * @return  the value of goods.picture
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.picture
	 * @param picture  the value for goods.picture
	 * @mbg.generated  Fri Jan 05 16:01:07 CST 2018
	 */
	public void setPicture(String picture) {
		this.picture = picture;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/*
	 * 编号
	 */
	private int id;
	/*
	 * 名称
	 */
	@Pattern(regexp="^[^><&#]{1,50}$",message="{pattern}")
	@NotNull(message="{notNull}")
	private String name;
	/*
	 * 价格
	 */
	@Min(value=1,message="必须大于或等�?1")
	private double price;
	/*
	 * 图片
	 */
	private String picture;
	
	public Goods() {
	}
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public double getPrice() {
		return price;
	}
	public void setPrice(double price) {
		this.price = price;
	}
	public String getPicture() {
		return picture;
	}
	public void setPicture(String picture) {
		this.picture = picture;
	}
	
	@Override
	public String toString() {
		return "id�?"+getId()+"，name�?"+getName()+"，price�?"+getPrice()+"，picture�?"+getPicture();
	}
}
